exclude:
- README.md

plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

theme: jekyll-theme-minimal
title: Dariush Ghaemi's homepage
description: Bookmark this to keep an eye on my project updates!

navigation_header:
- title: Home
  url: /



